import '../Models/words_data.dart';

import '../constants.dart';
import '../data.dart';

List<WordsData> adjectives = [
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'مُسْلِمٌ',
    urdu: 'مسلمان',
    eng: 'Muslim',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'کَافِرٌ',
    urdu: 'کافر',
    eng: 'A disbeliever',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'مُنَافِقٌ',
    urdu: 'منافق',
    eng: 'A hypocrite',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'فَاسِقٌ',
    urdu: 'فاسق',
    eng: 'The transgressor',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'خَاسِرُوْنَ',
    urdu: 'خسارہ پانے والے',
    eng: 'Loss-making',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مُشْرِکُوْنَ',
    urdu: 'مُشرک لوگ',
    eng: 'Polytheist people',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'مُتَوکَّلُوْنَ',
    urdu: 'بھروسہ کرنے والے',
    eng: 'Trustees',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَصْحٰبُ النَّارِ',
    urdu: 'آگ والے',
    eng: 'The fire ones',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'غَافِلُوْنَ',
    urdu: 'غافل لوگ',
    eng: 'Oblivious people',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'مُؤمِنُوْنَ',
    urdu: 'مؤمن لوگ',
    eng: 'Belivers',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'صَابِرُوْنَ',
    urdu: 'صبر کرنے والے',
    eng: 'The patient ones',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'مُمْتَرِیْنَ',
    urdu: 'انکار کرنے والے',
    eng: 'Those who refuse',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'سَابِقُوْنَ',
    urdu: 'سبقت کرنے والے',
    eng: 'The leading ones',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'الذَاکِرُوْنَ',
    urdu: 'ذکر کرنے والے',
    eng: 'The who mention',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'مُفْلِحُوْنَ',
    urdu: 'کامیاب',
    eng: 'Successful',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مُھْتَدُوْنَ',
    urdu: 'ہدایت پانے والے',
    eng: 'Guided',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'خَاشِعُوْنَ',
    urdu: 'خشوع کرنے والے',
    eng: 'The humble ones',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'مُخْتَلِفُوْنَ',
    urdu: 'اختلاف کرنے والے',
    eng: 'Dissenters',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[11].topic,
    engheading: twoTopics[11].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'عَابِدُوْنَ',
    urdu: 'عبادت کرنے والے',
    eng: 'Worshippers',
    g: ' ',
  ),
];
