import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> animal = [
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اَنْعَامٌ',
    urdu: 'جانور',
    eng: 'animals',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'طَیْرٌ',
    urdu: 'پرندے',
    eng: 'birds',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلْفِیْلُ',
    urdu: 'ہاتھی',
    eng: 'The elephant',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَلنَّاقَةُ',
    urdu: 'اونٹنی',
    eng: 'The Camel',
    g: '(F)',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَلْبَقَرَةُ',
    urdu: 'گائے',
    eng: 'The Cow',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلثُّعْبَانُ',
    urdu: 'اژدھا',
    eng: 'the serpent',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلْکَلْبُ',
    urdu: 'کتا',
    eng: 'The dog',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلْقِرَدُ',
    urdu: 'بندر',
    eng: 'The monkey',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'حِمَارٌ',
    urdu: 'گدھا',
    eng: 'donkey',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اِبِلِ',
    urdu: 'اونٹ',
    eng: 'Camel',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلْعَنْکَبُوْتُ',
    urdu: 'مکڑی',
    eng: 'the spider',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلنَّحْلُ',
    urdu: 'شہد کی مکھی',
    eng: 'The bee',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلْنَمْلَةُ',
    urdu: 'چیونٹی',
    eng: 'The ant',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَبَابِیْلُ',
    urdu: 'ابابیل',
    eng: 'ababeel',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَلْغُرَابُ',
    urdu: 'کوّا',
    eng: 'The crow',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلْھُدْھُدْ',
    urdu: 'ہدہد',
    eng: 'the hudhud',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلْحُوْتُ',
    urdu: 'مچھلی',
    eng: 'The fish',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلضَّأْنِ',
    urdu: 'بھیڑ',
    eng: 'The sheep',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'أَلْمَعْز',
    urdu: 'بکری',
    eng: 'The goat',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'خِنْزِیْر',
    urdu: 'سور',
    eng: 'Pig',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[5].topic,
    engheading: twoTopics[5].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلسَّبُعُ',
    urdu: 'درندہ',
    eng: 'the wild animal',
    g: ' ',
  ),
];
