import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> blessings = [
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'تُرَابٌ',
    urdu: 'مٹی',
    eng: 'soil',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'طِیْنٌ',
    urdu: 'چکنی مٹی',
    eng: 'clay soil',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'سَمَاءٌ/ سَمَوٰتٌ',
    urdu: 'آسمان',
    eng: 'sky',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'شَمْسٌ',
    urdu: 'سورج',
    eng: 'sun',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'قَمَرٌ',
    urdu: 'چاند',
    eng: 'moon',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'نَجْمٌ',
    urdu: 'ستارے',
    eng: 'stars',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'ھِلَالٌ',
    urdu: 'چاند',
    eng: 'moon',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'صَحْرٌ',
    urdu: 'چٹان',
    eng: 'rock',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَرْضٌ',
    urdu: 'زمین',
    eng: 'earth',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'شَجَرَةٌ',
    urdu: 'درخت',
    eng: 'tree',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مَآءٌ',
    urdu: 'پانی',
    eng: 'Water',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'لَبْنٌ',
    urdu: 'دودھ',
    eng: 'milk',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'عَسَلٌ',
    urdu: 'شہد',
    eng: 'honey',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'جَبَلٌ',
    urdu: 'پہاڑ',
    eng: 'mountain',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'حَجَرَةٌ',
    urdu: 'پتھر',
    eng: 'stone',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'کَھْفٌ',
    urdu: 'غار',
    eng: 'cave',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'لُؤْلُؤٌ',
    urdu: 'موتی',
    eng: 'pearl',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'نَھْرٌ',
    urdu: 'دریا',
    eng: 'river',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'مَوْجٌ',
    urdu: 'لہر',
    eng: 'wave',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'شَاطِئٌی',
    urdu: 'ساحل/ کنارہ',
    eng: 'edge',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'صَحْرَآءُ',
    urdu: 'ریگستان',
    eng: 'desert',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'وَرَقَةٌ',
    urdu: 'پتا',
    eng: 'leaf',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'نَوْمٌ',
    urdu: 'نیند',
    eng: 'sleep',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'زَھْرَةٌ',
    urdu: 'شان و شوکت',
    eng: 'splendour',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'سَبِیْلٌ',
    urdu: 'راستہ',
    eng: 'path',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'بَحْرٌ',
    urdu: 'دریا/ سمندر',
    eng: 'sea',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'رِیحٌ',
    urdu: 'ہوا',
    eng: 'wind',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'مَطَرٌ/ غَیْثٌ',
    urdu: 'بارش',
    eng: 'rain',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'حَرَارَةٌ',
    urdu: 'تپش',
    eng: 'heat/ hot',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[9].topic,
    engheading: twoTopics[9].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَلْحَبُّ',
    urdu: 'اناج',
    eng: 'grain',
    g: ' ',
  ),
];
