import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> bodyparts = [
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'قَلْبٌ',
    urdu: 'دل',
    eng: 'heart',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'وَجْہٌ',
    urdu: 'چہرہ',
    eng: 'face',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بَصَرٌ',
    urdu: 'آنکھ/ نظر',
    eng: 'sight',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اُذُنٌ',
    urdu: 'کان',
    eng: 'ear',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَصَابِعَ',
    urdu: 'انگلیاں',
    eng: 'fingers',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'رَقَبَةٌ',
    urdu: 'گردن',
    eng: 'neck',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'لِسَانٌ',
    urdu: 'زبان',
    eng: 'tongue',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'شَفَتَیْنِ',
    urdu: 'ہونٹ',
    eng: 'lips',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'کَعْبَیْنِ',
    urdu: 'ٹخنے',
    eng: 'ankles',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'بَطَنٌ',
    urdu: 'پیٹ',
    eng: 'belly',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'صَدْرٌ',
    urdu: 'سینہ',
    eng: 'chest',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'رَاْسٌ',
    urdu: 'سر',
    eng: 'head',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'أنْفٌ',
    urdu: 'ناک',
    eng: 'nose',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'یَدٌ',
    urdu: 'ہاتھ',
    eng: 'hand',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'فُؤَادُ/ أَفْئِدَةِ',
    urdu: 'دل',
    eng: 'heart',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مَرَافِقٌ',
    urdu: 'کہنیاں',
    eng: 'elbow',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'عَیْنٌ',
    urdu: 'آنکھ',
    eng: 'eye',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'رِجْلٌ',
    urdu: 'ٹانگ',
    eng: 'leg',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'قَدَمٌ',
    urdu: 'پاؤں',
    eng: 'feet',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[6].topic,
    engheading: twoTopics[6].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'سِنٌّ',
    urdu: 'دانت',
    eng: 'teeth',
    g: ' ',
  ),
];
