import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> color = [
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اَلْوَانُ',
    urdu: 'بہت سارے رنگ',
    eng: 'Colors',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'لَوْنٌ',
    urdu: 'رنگ',
    eng: 'Color',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَحْمَرٌ',
    urdu: 'لال/ سرخ',
    eng: 'Red',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'صَفْرَآءُ (اَصْفَرٌ)',
    urdu: 'پیلی/ زرد',
    eng: 'Yellow',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَخْضَرٌ',
    urdu: 'سبز/ ہرا',
    eng: 'Green',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَزْرَقٌ',
    urdu: 'نیلا',
    eng: 'Blue',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'فَاقِعٌ',
    urdu: 'چمکدار/ روشن',
    eng: 'Bright',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَسْوَدٌ',
    urdu: 'کالا',
    eng: 'Black',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[0].topic,
    engheading: twoTopics[0].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَبْیَضٌ',
    urdu: 'سفید',
    eng: 'White',
    g: ' ',
  ),
];
