import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> deeds = [
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اَلْحَسَنٰتُ',
    urdu: 'اچھائیاں',
    eng: 'good things',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلسَّیِّئَآتُ',
    urdu: 'برائیاں',
    eng: 'evils',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلْخَیْرَاتُ',
    urdu: 'بھلائی کے کام',
    eng: 'the good deeds',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَلْمَعْرُوْفُ',
    urdu: 'نیکی',
    eng: 'the goodness',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'خَیْرٌ',
    urdu: 'بہتر',
    eng: 'a better',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلشَّرُّ',
    urdu: 'شر/ برائی',
    eng: 'the evil',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلسُّوْٓءُ',
    urdu: 'برائی',
    eng: 'the evil',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلْقَطْعُ',
    urdu: 'علیحدہ کرنا/ کاٹنا',
    eng: 'to separate',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'حُوْبًا',
    urdu: 'گناہ',
    eng: 'a sin',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'بِئْسَ',
    urdu: 'کتنا ہی برا',
    eng: 'how evil',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'نِعَمَ',
    urdu: 'کتنا ہی اچھا',
    eng: 'how good',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'جُنَاحٌ',
    urdu: 'کوئی گناہ',
    eng: 'any sin',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'أَجْرٌ',
    urdu: 'ثواب',
    eng: 'a reward',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَلْبِرُّ',
    urdu: 'اچھائی/ نیکی',
    eng: 'the goodness',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'لُمَزَةٍ',
    urdu: 'چغل خور',
    eng: 'a backbitter',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلصَّلٰوةُ',
    urdu: 'نماز/ دعا',
    eng: 'the prayer',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلصَّوْمُ',
    urdu: 'روزہ',
    eng: 'the fast',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'شَھَادَةٌ',
    urdu: 'گواہی',
    eng: 'the testimony',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَلطَّاعَةُ',
    urdu: 'فرمانبرداری',
    eng: 'the obedience',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'فُسُوْقٌ',
    urdu: 'نافرمانی',
    eng: 'a disobedience',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلضَّلٰلَةُ',
    urdu: 'گمراہی',
    eng: 'the astraying',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلْھُدٰی',
    urdu: 'ہدایت',
    eng: 'the guidance',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلرِّبَوٰا',
    urdu: 'سود',
    eng: 'the usury/ interest',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَلْبَیْعُ',
    urdu: 'تجارت',
    eng: 'the trade',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَلْغَیْظُ',
    urdu: 'سخت غصہ',
    eng: 'the anger',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلْفَحْشَآءُ',
    urdu: 'بےحیائی',
    eng: 'the shameful',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'ذَنْبٌ',
    urdu: 'گناہ',
    eng: 'a sin',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بَاْسٌ',
    urdu: 'جنگ',
    eng: 'a battle',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'ذِکْرٌ',
    urdu: 'یاد',
    eng: 'a reminder',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[8].topic,
    engheading: twoTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَلْکَذِبُ',
    urdu: 'جھوٹ',
    eng: 'the lie',
    g: ' ',
  ),
];
