import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> fire = [
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'نَارٌ',
    urdu: 'آگ',
    eng: 'Fire',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'جَھَنَّمُ',
    urdu: 'دوزخ',
    eng: 'Hell',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'جَحِیْمٌ',
    urdu: 'دوزخ',
    eng: 'Hell',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'سَعِیْرٌ',
    urdu: 'بھڑکتی آگ',
    eng: 'Blazing Fire',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'سَقَرٌ',
    urdu: 'جہنم کی لپٹ',
    eng: 'Flame of Hell',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلْحامِیَةُ',
    urdu: 'دہکتی ہوئی',
    eng: 'Intensely hot',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلْحُطَمَةُ',
    urdu: 'چکنا چور کر دینے والی جگہ',
    eng: 'The shattering place',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَلْھَاوِیَةُ',
    urdu: 'گہری کھائی',
    eng: 'The deep Ditch',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'حَارٌ',
    urdu: 'گرم',
    eng: 'Hot',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'نَزَّاعَةً',
    urdu: 'ادھیڑنے والی',
    eng: 'Stripping off',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مُوقَدَةٌ',
    urdu: 'بھڑکائی ہوئی',
    eng: 'Inflamed',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'وَیْلٌ',
    urdu: 'تباہی/ جہنم کی وادی',
    eng: 'Woe/ Rui',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بِئْسَ المِھَادُ',
    urdu: 'بہت ہی برا ٹھکانہ',
    eng: 'Evil resting place',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[3].topic,
    engheading: twoTopics[3].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'بِئْسَ الْمَصِیرُ',
    urdu: 'بد ترین جگہ',
    eng: 'The worst Place',
    g: ' ',
  ),
];
