import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> fruits = [
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'فَاکِھَةٌ/ ثَمَرٌ',
    urdu: 'پھل',
    eng: 'Fruit',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَلتِّیْنُ',
    urdu: 'انجیر',
    eng: 'The fig',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'رُمَّانٌ',
    urdu: 'انار',
    eng: 'Pomegranate',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'الزَّیْتُوْنُ',
    urdu: 'زیتون',
    eng: 'The Olive',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَلْعِنَبُ',
    urdu: 'انگور',
    eng: 'The Grapes',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'طَلَحٌ',
    urdu: 'کیلا',
    eng: 'Banana',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'رَطْبٌ',
    urdu: 'تر کھجور',
    eng: 'Ripe Date',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[1].topic,
    engheading: twoTopics[1].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'نَخْلٌ',
    urdu: 'کھجور',
    eng: 'Date',
    g: ' ',
  )
];
