import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> jannah = [
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'جَنَّةٌ',
    urdu: 'باغ',
    eng: 'Garden',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'جَنّٰتُ عَدْنٍ',
    urdu: 'سدا بہار جنتیں',
    eng: 'Evergreen Heavens',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'جَنَّةُ الْفِرْدَوْسِ',
    urdu: 'سب سے اعلٰی جنت',
    eng: 'The highest heaven',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'جَنّٰتِ النَّعِیْمِ',
    urdu: 'نعمت بھرے باغات',
    eng: 'Gardens of bliss',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'جَنَّةُ الْمَاْوٰی',
    urdu: 'بہت عمدہ ٹھکانہ',
    eng: 'The abode garden',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مَقَامٍ اَمِیْنٍ',
    urdu: 'امن و عافیت کی جگہ',
    eng: 'A secure place',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'دَارُالْمُقَامَةِ',
    urdu: 'ہمیشہ رہنے کا مقام',
    eng: 'The permanent abode',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'دَارُالْخُلْدِ',
    urdu: 'ہمیشہ رہنے کا گھر ',
    eng: 'The permanent abode',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'دَارُالسَّلَامِ',
    urdu: 'سلامتی والا گھر',
    eng: 'the home of peace',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'دَارُالْقَرَارِ',
    urdu: 'راحت کی جگہ',
    eng: 'The permanent place',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'دَارُالْاٰخِرَةِ',
    urdu: 'آخرت کا گھر',
    eng: 'The Last Home',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'دَارُالْمُتَّقِیْنَ',
    urdu: 'پرہیزگاروں کا گھر',
    eng: 'The home of God-Fearing',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'دَارُالْحَیَوانَ',
    urdu: 'اصلی زندگی کا گھر',
    eng: 'The abode of hereafter',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[4].topic,
    engheading: twoTopics[4].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'مَقْعَدِصِدْقٍ',
    urdu: 'سچ کی مجلس/ باعزت مجلس',
    eng: 'Seat of honor',
    g: ' ',
  )
];
