import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> relatives = [
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اُمَّھَاتٌ',
    urdu: 'مائیں',
    eng: 'mothers',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'بَنَاتٌ',
    urdu: 'بیٹیاں',
    eng: 'daughters',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَخَوَاتٌ',
    urdu: 'بہنیں',
    eng: 'sisters',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'عَمَّاتٌ',
    urdu: 'پھوپھیاں',
    eng: 'aunts',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'خَالَاتٌ',
    urdu: 'خالائیں',
    eng: 'maternal aunts',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'بَنٰتُ الْاَخِ',
    urdu: 'بھتیجیاں',
    eng: 'nieces',
    g: '(F)',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'بَنٰتُ الْاُخْتِ',
    urdu: 'بھانجیاں',
    eng: 'nieces',
    g: '(F)',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'رِجَالٌ',
    urdu: 'مرد',
    eng: 'Men',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'نِسَآءٌ',
    urdu: 'عورتیں',
    eng: 'women',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'بِنْتُ',
    urdu: 'لڑکی',
    eng: 'A girl',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'وَلَدٌ',
    urdu: 'لڑکا',
    eng: 'A boy',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'أِبْنُ',
    urdu: 'بیٹا',
    eng: 'son',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'أَزْوَاجٌ',
    urdu: 'بیویاں - شوہر',
    eng: 'husbands and wives',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'رَبَائِبٌ',
    urdu: 'بچیاں',
    eng: 'girls',
    g: '',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'وَالِدَانِ',
    urdu: 'والدین',
    eng: 'parents',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[7].topic,
    engheading: twoTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'أَخٌ',
    urdu: 'بھائی',
    eng: 'brother',
    g: ' ',
  )
];
