import '../Models/words_data.dart';
import '../constants.dart';
import '../data.dart';

List<WordsData> veg = [
  WordsData(
    urduheading: twoTopics[2].topic,
    engheading: twoTopics[2].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'بَقْلٌ',
    urdu: 'ترکاری',
    eng: 'Herb',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[2].topic,
    engheading: twoTopics[2].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'قِثَّآءٌ',
    urdu: 'کھیرا/ ککڑی',
    eng: 'Cucumber',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[2].topic,
    engheading: twoTopics[2].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'فُوْمٌ',
    urdu: 'لہسن',
    eng: 'Garlic',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[2].topic,
    engheading: twoTopics[2].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'بَصَلٌ',
    urdu: 'پیاز',
    eng: 'Onion',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[2].topic,
    engheading: twoTopics[2].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَقْطِیْنٌ',
    urdu: 'کدو',
    eng: 'Pumpkin',
    g: ' ',
  ),
  WordsData(
    urduheading: twoTopics[2].topic,
    engheading: twoTopics[2].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'زَنْجَبِیْلٌ',
    urdu: 'ادرک',
    eng: 'Ginger',
    g: ' ',
  )
];
