import '../Models/words_data.dart';

import '../constants.dart';
import '../data.dart';

List<WordsData> pastA = [
  WordsData(
    urduheading: threeTopics[6].topic,
    engheading: threeTopics[6].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'صَدَقَ اللّٰہ',
    urdu: 'اللّٰہ نے سچ کہا',
    eng: 'Allah spoke the truth',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[6].topic,
    engheading: threeTopics[6].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'فَتَحُ اللّٰہ',
    urdu: 'اللّٰہ نے فتح دی',
    eng: 'Allah gave victory',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[6].topic,
    engheading: threeTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'رَجَعَ موسیٰ',
    urdu: 'موسیٰ علیہ السلام لوٹ آئے',
    eng: 'Moses returned',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[6].topic,
    engheading: threeTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'مَارَبِحَتْ',
    urdu: 'کچھ نفع نہ دیا',
    eng: 'not give any benefit',
    g: ' ',
  ),
];

List<WordsData> pastP = [
  WordsData(
    urduheading: threeTopics[7].topic,
    engheading: threeTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'خُلِقَ الاِنْسَانُ',
    urdu: 'انسان پیدا کیا گیا',
    eng: 'Man was created',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[7].topic,
    engheading: threeTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'قُرِئ القُرْآنُ',
    urdu: 'جب قرآن پڑھا جائے',
    eng: 'when Quran is recited',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[7].topic,
    engheading: threeTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'کُتِبَ عَلِیْکُم الصِیامُ',
    urdu: 'تم پر روزے فرض کیے گئے',
    eng: 'fasting imposed on you',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[7].topic,
    engheading: threeTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'قُتِلَ الکافِرُوْنَ',
    urdu: 'کافروں کو قتل کیا گیا',
    eng: 'infidels were killed',
    g: ' ',
  ),
];

List<WordsData> pfA = [
  WordsData(
    urduheading: threeTopics[8].topic,
    engheading: threeTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'یَغْفِرُ اللّٰہُ الزنوبَ',
    urdu: 'اللّٰہ گناہوں کو بخش دیتا ہے',
    eng: 'Allah forgives sins',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[8].topic,
    engheading: threeTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'یَرْزُقُنا اللّٰہ',
    urdu: 'اللّٰہ ہمیں رزق دیتا ہے',
    eng: 'Allah gives us sustenance',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[8].topic,
    engheading: threeTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'یَشْرَحُ اللّٰہٗ صدْرَنَا',
    urdu: 'اللّٰہ نے ہمارا سینہ کھول دیا',
    eng: 'Allah opened our chest',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[8].topic,
    engheading: threeTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'لِمَ کَفَرْتُمْ باللّٰہِ',
    urdu: 'تم نے اللّٰہ کے ساتھ کفر کیوں کیا',
    eng: 'why did you disbelieve in Allah',
    g: ' ',
  ),
];

List<WordsData> pfP = [
  WordsData(
    urduheading: threeTopics[9].topic,
    engheading: threeTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'یُعْرَفُ المُجرمُوْنَ',
    urdu: 'جرم پہچانے جائیں گے',
    eng: 'culprits will be identified',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[9].topic,
    engheading: threeTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'لَا تُقْبَلُ مِنْھَا شَفَاعةٌ',
    urdu: 'ان سے سفارش قبول نہ ہو گی',
    eng: 'recommendation not be accepted',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[9].topic,
    engheading: threeTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'تُسَلُنَّ یومَئذٍ',
    urdu: 'اُس دن تم سے سوال کیا جائی گا',
    eng: 'on that day you will be questioned',
    g: ' ',
  )
];
