import '../Models/words_data.dart';

import '../constants.dart';
import '../data.dart';

List<WordsData> ajwaf = [
  WordsData(
    urduheading: threeTopics[5].topic,
    engheading: threeTopics[5].eng.capitalize(),
    subheading: 'اجوف (واوی)',
    color: red,
    n: '1',
    name: 'قَال',
    urdu: 'کہنا',
    eng: 'to say',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[5].topic,
    engheading: threeTopics[5].eng.capitalize(),
    subheading: 'اجوف (واوی)',
    color: yellow,
    n: '2',
    name: 'خَافَ',
    urdu: 'ڈرنا',
    eng: 'fear',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[5].topic,
    engheading: threeTopics[5].eng.capitalize(),
    subheading: 'اجوف (واوی)',
    color: torquise,
    n: '3',
    name: 'شَاءَ',
    urdu: 'چاہنا',
    eng: 'liking',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[5].topic,
    engheading: threeTopics[5].eng.capitalize(),
    subheading: 'اجوف (یائی)',
    color: orange,
    n: '4',
    name: 'زَادَ',
    urdu: 'زیادہ کرنا',
    eng: 'to do more',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[5].topic,
    engheading: threeTopics[5].eng.capitalize(),
    subheading: 'اجوف (یائی)',
    color: darkGreen,
    n: '5',
    name: 'جَاءَ',
    urdu: 'آنا',
    eng: 'he came',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[5].topic,
    engheading: threeTopics[5].eng.capitalize(),
    subheading: 'اجوف (یائی)',
    color: red,
    n: '6',
    name: 'بَاعَ',
    urdu: 'بیچنا',
    eng: 'to sell',
    g: ' ',
  ),
];
