import '../Models/words_data.dart';

import '../constants.dart';
import '../data.dart';

List<WordsData> past = [
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: red,
    n: '1',
    name: 'خَلَقَ',
    urdu: 'اُس نے پیدا کیا',
    eng: 'he created',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: yellow,
    n: '2',
    name: 'فَتَحَ',
    urdu: 'اُس نے کھولا',
    eng: 'he opened',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: torquise,
    n: '3',
    name: 'رَفَعَ',
    urdu: 'اُس نے بلند کیا',
    eng: 'he raised',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: orange,
    n: '4',
    name: 'غَفَرَ',
    urdu: 'اُس نے بخشا',
    eng: 'he forgave',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: darkGreen,
    n: '5',
    name: 'غَفَلَ',
    urdu: 'وہ غافل ہوا',
    eng: 'he was oblivious',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: red,
    n: '6',
    name: 'سَجَدَ',
    urdu: 'اُس نے سجدہ کیا',
    eng: 'he prostrated',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: red,
    n: '1',
    name: 'ضَرَبَ',
    urdu: 'اُس نے مارا',
    eng: 'he killed',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: yellow,
    n: '2',
    name: 'خَرَجَ',
    urdu: 'وہ نکلا',
    eng: 'he came out',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: torquise,
    n: '3',
    name: 'رَزَقَ',
    urdu: 'اُس نے رزق دیا',
    eng: 'he granted',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: orange,
    n: '4',
    name: 'جَعَلَ',
    urdu: 'اُس نے بنایا',
    eng: 'he made it',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: darkGreen,
    n: '5',
    name: 'صَبَرَ',
    urdu: 'اُس نے صبر کیا',
    eng: 'he was patient',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: red,
    n: '6',
    name: 'عَبَدَ',
    urdu: 'اُس نے عبادت کی',
    eng: 'he worshiped',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: red,
    n: '1',
    name: 'حَشَرَ',
    urdu: 'اُس نے اکٹھا کیا',
    eng: 'he gathered',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: yellow,
    n: '2',
    name: 'عَقَلَ',
    urdu: 'اُس نے عقل سے کام لیا',
    eng: 'he acted wisely',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: torquise,
    n: '3',
    name: 'جَلَسَ',
    urdu: 'وہ بیٹھا',
    eng: 'he sat down',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: orange,
    n: '4',
    name: 'دَخَلَ',
    urdu: 'وہ داخل ہوا',
    eng: 'he entered',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: darkGreen,
    n: '5',
    name: 'ذَھَبَ',
    urdu: 'وہ گیا',
    eng: 'he goes',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: red,
    n: '6',
    name: 'ظَلَمَ',
    urdu: 'اُس نے ظلم کیا',
    eng: 'he did injustice',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '1st pattern - (فَعَلَ)',
    color: red,
    n: '6',
    name: 'نَجَحَ',
    urdu: 'وہ کامیاب ہوا',
    eng: 'he succeeded',
    g: ' ',
  ),

  ///////2nd pattern
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'فَرِحَ',
    urdu: 'وہ خوش ہوا',
    eng: 'he was happy',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'عَلِمَ',
    urdu: 'اُس نے جانا',
    eng: 'he found out',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'قَدِمَ',
    urdu: 'وہ آیا',
    eng: 'he came',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'سَمِعَ',
    urdu: 'اُس نے سنا',
    eng: 'he heard',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'شَرِبَ',
    urdu: 'اُس نے پیا',
    eng: 'he drank',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'رَحِمَ',
    urdu: 'اُس نے رحم کیا',
    eng: 'he showed mercy',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'شَھِدَ',
    urdu: 'اُس نے گواہی دی',
    eng: 'he testified',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'مَرِضَ',
    urdu: 'وہ بیمار ہوا',
    eng: 'he got sick',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'عَمِلَ',
    urdu: 'اُس نے عمل کیا',
    eng: 'he acted',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'ضَحِکَ',
    urdu: 'وہ ہنسا',
    eng: 'he laughed',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'حَمِدَ',
    urdu: 'اُس نے حمد کی',
    eng: 'he praised',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'حَسِبَ',
    urdu: 'اُس نے گمان کیا',
    eng: 'he assumed',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'حَفِظَ',
    urdu: 'اُس نے یاد کیا',
    eng: 'he recalled',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'رَکِبَ',
    urdu: 'وہ سوار ہوا',
    eng: 'he rode',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '2nd pattern - (فَعِلَ)',
    color: red,
    n: '6',
    name: 'قَبِلَ',
    urdu: 'اُس نے قبول کیا',
    eng: 'he accepted',
    g: ' ',
  ),

  ///////3rd pattern
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '3rd pattern - (فَعُلَ)',
    color: red,
    n: '6',
    name: 'فَرِحَ',
    urdu: 'وہ قریب ہوا',
    eng: 'he came closer',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '3rd pattern - (فَعُلَ)',
    color: red,
    n: '6',
    name: 'کَرُمَ',
    urdu: 'وہ باعزت ہوا',
    eng: 'he was honoured',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '3rd pattern - (فَعُلَ)',
    color: red,
    n: '6',
    name: 'ضَعُفَ',
    urdu: 'وہ کمزور ہوا',
    eng: 'he became weak',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '3rd pattern - (فَعُلَ)',
    color: red,
    n: '6',
    name: 'بَعُدَ',
    urdu: 'وہ دور ہوا',
    eng: 'he walked away',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[1].topic,
    engheading: threeTopics[1].eng.capitalize(),
    subheading: '3rd pattern - (فَعُلَ)',
    color: red,
    n: '6',
    name: 'ثَقُلَ',
    urdu: 'وہ بھاری ہوا',
    eng: 'he became heavy',
    g: ' ',
  ),
];
