import '../Models/words_data.dart';

import '../constants.dart';
import '../data.dart';

List<WordsData> pfpatterns = [
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'یَخْلُقُ',
    urdu: 'وہ پیدا کرتا ہے یا کرے گا',
    eng: 'he creates',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'یَفْتَحُ',
    urdu: 'وہ کھولتا ہے یا کھولے گا',
    eng: 'he opens',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'یَرْفَعُ',
    urdu: 'وہ اٹھاتا ہے یااٹھائے گا',
    eng: 'he picks up',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'یَغْفِرُ',
    urdu: 'وہ بخشتا ہے یا بخشے گا',
    eng: 'he forgives',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَغْفُلُ',
    urdu: 'وہ غافل ہوتا ہے یا ہو گا',
    eng: 'he is oblivious',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَسْجُدُ',
    urdu: 'وہ سجدہ کرتا ہے یا کرے گا',
    eng: 'he prostrates',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'یَضْرِبُ',
    urdu: 'وہ مارتا ہے یا مارے گا',
    eng: 'he kills',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'یَخْرُجُ',
    urdu: 'وہ نکلتا ہے یا نکلے گا',
    eng: 'he leaves',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'یَرْزُقُ',
    urdu: 'وہ عطا کرتا ہے یا کرے گا',
    eng: 'he bestows',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'یَفْرَحُ',
    urdu: 'وہ خوش ہوتا ہے یا ہو گا',
    eng: 'he is happy',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'یَعْلَمُ',
    urdu: 'وہ جانتا ہے یا جانے گا',
    eng: 'he knows',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَسْمَعَ',
    urdu: 'ْوہ سنتا ہے یا سنے گا',
    eng: 'he listens',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَشْرَبُ',
    urdu: 'وہ پیتا ہے یا پیے گا',
    eng: 'he drinks',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'یَرْحَمُ',
    urdu: 'وہ رحم کرتا ہے یا رحم کرے گا',
    eng: 'he shows mercy',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'یَشْھَدُ',
    urdu: 'وہ گواہی دیتا ہے یا دے گا',
    eng: 'he testifies',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'یَعْمَلُ',
    urdu: 'وہ عمل کرتا ہے یا کرے گا',
    eng: 'he acts',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَضْحَکَ',
    urdu: 'وہ ہنستا ہے یا ہنسے گا',
    eng: 'he laughs',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَقْرَبُ',
    urdu: 'وہ قریب ہوتا ہے یا ہو گا',
    eng: 'he is near',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[2].topic,
    engheading: threeTopics[2].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'یَکْرُمُ',
    urdu: 'وہ باعزت ہوتا ہے یا ہو گا',
    eng: 'he shows mercy',
    g: ' ',
  ),
];
