import '../Models/words_data.dart';

import '../constants.dart';
import '../data.dart';

List<WordsData> vpatterns = [
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '1st pattern - اِفْعَال (مادہ)',
    color: red,
    n: '1',
    name: 'اَنْزَلَ',
    urdu: 'اتارنا',
    eng: 'take off',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '1st pattern - اِفْعَال (مادہ)',
    color: yellow,
    n: '2',
    name: 'اَخْرَجَ',
    urdu: 'نکلنا',
    eng: 'take out',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '1st pattern - اِفْعَال (مادہ)',
    color: torquise,
    n: '3',
    name: 'اَدْخَلَ',
    urdu: 'داخل کرنا',
    eng: 'to insert',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '2nd pattern - تَفْعِیْل (مادہ)',
    color: orange,
    n: '4',
    name: 'اَعْلَّمَ',
    urdu: 'سکھانا',
    eng: 'teach',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '2nd pattern - تَفْعِیْل (مادہ)',
    color: darkGreen,
    n: '5',
    name: 'نَزَّلَ',
    urdu: 'نازل کرنا',
    eng: 'to reveal',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '2nd pattern - تَفْعِیْل (مادہ)',
    color: red,
    n: '6',
    name: 'سَبَّحَ',
    urdu: 'تسبیح کرنا',
    eng: 'to glorify',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '3rd pattern - مُفَاعَلَہٗ (مادہ)',
    color: orange,
    n: '4',
    name: 'نَافَقَ',
    urdu: 'منافق ہوا',
    eng: 'you are a hypocrite',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '3rd pattern - مُفَاعَلَہٗ (مادہ)',
    color: darkGreen,
    n: '5',
    name: 'جَاھَدَ',
    urdu: 'جہاد کرنا',
    eng: 'doing jihad',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '3rd pattern - مُفَاعَلَہٗ (مادہ)',
    color: red,
    n: '6',
    name: 'حَافَظَ',
    urdu: 'حفاظت کرنا',
    eng: 'to protect',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '4th pattern - تفَعُّل (مادہ)',
    color: orange,
    n: '4',
    name: 'تعَلَّم',
    urdu: 'سکھنا',
    eng: 'learning',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '4th pattern - تفَعُّل (مادہ)',
    color: darkGreen,
    n: '5',
    name: 'تذکَّرَ',
    urdu: 'یاد کرنا',
    eng: 'to remember',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '4th pattern - تفَعُّل (مادہ)',
    color: red,
    n: '6',
    name: 'تفکَّرَ',
    urdu: 'غور و فکر کرنا',
    eng: 'to ponder',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '5th pattern - تفاعُل (مادہ)',
    color: orange,
    n: '4',
    name: 'تَدَارَسَ',
    urdu: 'باہم پڑھنا',
    eng: 'read together',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '5th pattern - تفاعُل (مادہ)',
    color: darkGreen,
    n: '5',
    name: 'تَنَاصَرَ',
    urdu: 'ایک دوسرے کی مدد کرنا',
    eng: 'helping each other',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '5th pattern - تفاعُل (مادہ)',
    color: red,
    n: '6',
    name: 'تَنَازَعَ',
    urdu: 'باہم جھگڑھنا',
    eng: 'to fight each other',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '6th pattern - اِفتعَال (مادہ)',
    color: orange,
    n: '4',
    name: 'اِصْطَبَرَ',
    urdu: 'صبر کرنا',
    eng: 'to be patient',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '6th pattern - اِفتعَال (مادہ)',
    color: darkGreen,
    n: '5',
    name: 'اِخْتَصَمَ',
    urdu: 'جھگڑا کرنا',
    eng: 'to argue',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '6th pattern - اِفتعَال (مادہ)',
    color: red,
    n: '6',
    name: 'اِخْتَلَفَ',
    urdu: 'اختلاف کرنا',
    eng: 'to disagree',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '7th pattern - انفعال (مادہ)',
    color: orange,
    n: '4',
    name: 'اِنکَسَرَ',
    urdu: 'ٹوٹ جانا',
    eng: 'break down',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '7th pattern - انفعال (مادہ)',
    color: darkGreen,
    n: '5',
    name: 'اِنْصَرَفَ',
    urdu: 'پھر جانا',
    eng: 'then go',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '7th pattern - انفعال (مادہ)',
    color: red,
    n: '6',
    name: 'اِنْطَلَقَ',
    urdu: 'چلنا',
    eng: 'walk',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '8th pattern - استفْعَال (مادہ)',
    color: orange,
    n: '4',
    name: 'اِستَغْفَرَ',
    urdu: 'بخشش مانگنا',
    eng: 'ask for forgiveness',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '8th pattern - استفْعَال (مادہ)',
    color: darkGreen,
    n: '5',
    name: 'اِسْتَکْبَرَ',
    urdu: 'تکبر کرنا',
    eng: 'to be arrogant',
    g: ' ',
  ),
  WordsData(
    urduheading: threeTopics[3].topic,
    engheading: threeTopics[3].eng.capitalize(),
    subheading: '8th pattern - استفْعَال (مادہ)',
    color: red,
    n: '6',
    name: 'اِستَطْعَمَ',
    urdu: 'کھانا طلب کرنا',
    eng: 'ask for food',
    g: ' ',
  ),
];
