import '../data.dart';
import 'words_data.dart';
import '../constants.dart';

List<WordsData> cond = [
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اِنَّ',
    urdu: 'بے شک',
    eng: 'For sure',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَنَّ',
    urdu: 'بے شک',
    eng: 'That',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'کَاَنَّ - کَاَنْ',
    urdu: 'گویا کہ/  جیسا کہ',
    eng: 'As thought/ As if',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'لَکِنَّ',
    urdu: 'لیکن',
    eng: 'But',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'لَیْتَ',
    urdu: 'کاش',
    eng: 'If Only',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'لَعَلَّ',
    urdu: 'شاید',
    eng: 'Maybe',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '6',
    name: 'بِأَنَّ - بِاَنْ',
    urdu: 'کیونکہ',
    eng: 'because',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '6',
    name: 'اَنْ',
    urdu: 'کہ',
    eng: 'That',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف مشبہ بالفعل',
    engheading: quranTopics[12].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '6',
    name: 'اِنْ',
    urdu: 'اگر',
    eng: 'if',
    g: ' ',
  ),
];
