import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> conjunc = [
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'وَ',
    urdu: 'اور',
    eng: 'and',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'فَ',
    urdu: 'پس',
    eng: 'then/ so',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'ثُمَّ',
    urdu: 'پھر',
    eng: 'then',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَوْ',
    urdu: 'یا',
    eng: 'or',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'حَتّٰی',
    urdu: 'یہاں تک کہ',
    eng: "till/ even",
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَمْ',
    urdu: 'یا',
    eng: 'or?',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'لَا',
    urdu: 'نہیں',
    eng: 'not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'لٰکِنْ',
    urdu: 'لیکن',
    eng: 'but',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'بَلْ',
    urdu: 'بلکہ',
    eng: "rather",
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف الْعَطف',
    engheading: quranTopics[6].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اِمَّا',
    urdu: 'خواہ/ یا',
    eng: 'or',
    g: ' ',
  )
];
