import '../constants.dart';
import 'words_data.dart';

List<WordsData> dp = [
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: red,
    n: '1',
    name: 'ھٰذَا',
    urdu: 'یہ (مذکر)',
    eng: 'This',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: yellow,
    n: '2',
    name: 'ھٰذَانِ',
    urdu: 'یہ دو (مذکر)',
    eng: 'These two',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: torquise,
    n: '3',
    name: 'ھٰذِہٖ',
    urdu: '(موٴنث) یہ',
    eng: 'This',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: orange,
    n: '4',
    name: 'ھَاتَانِ',
    urdu: 'یہ دو (موٴنث)',
    eng: 'These Two',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: darkGreen,
    n: '5',
    name: 'ھٰؤُلَآءِ',
    urdu: '(مذکر و مؤنث) یہ سب',
    eng: 'All of These',
    g: '(M+F)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: red,
    n: '6',
    name: 'ذٰلِکَ',
    urdu: 'وہ (مذکر)',
    eng: 'That',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: yellow,
    n: '7',
    name: 'ذٰانِکَ',
    urdu: 'وہ دو (مذکر)',
    eng: 'Both of those',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: torquise,
    n: '8',
    name: 'تِلْکَ',
    urdu: 'وہ (موٴنث)',
    eng: 'That',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: orange,
    n: '9',
    name: 'تَانِکَ',
    urdu: 'وہ دو (مؤنث)',
    eng: 'Both of those',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'رفع',
    color: darkGreen,
    n: '10',
    name: 'اُولٓئِکَ',
    urdu: 'وہ سب (مذکر و مؤنث)',
    eng: 'All of Those',
    g: '',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'نصب و جر',
    color: red,
    n: '11',
    name: 'ھٰذَیْنِ',
    urdu: 'یہ دو (مذکر)',
    eng: 'These two',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'نصب و جر',
    color: yellow,
    n: '12',
    name: 'ھَاتَیْنِ',
    urdu: '(مؤنث) یہ دو',
    eng: 'These two',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'نصب و جر',
    color: torquise,
    n: '13',
    name: 'ذَیْنِکَ',
    urdu: ' وہ دو (مذکر)',
    eng: 'Both of those',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء اشارہ قریب و بعید',
    engheading: 'Demonstrative Pronouns',
    subheading: 'نصب و جر',
    color: orange,
    n: '14',
    name: 'تَیْنِکَ',
    urdu: 'وہ دو (مؤنث)',
    eng: 'Both of those',
    g: '(F)',
  ),
];
