import 'words_data.dart';

import '../constants.dart';

List<WordsData> internounwithprepo = [
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: red,
    n: '1',
    name: 'عَمَّ',
    urdu: ' کس کے بارے میں',
    eng: 'About whom',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: yellow,
    n: '2',
    name: 'لِمَ',
    urdu: 'کس لیے',
    eng: 'For what',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: torquise,
    n: '3',
    name: 'مِمَّ',
    urdu: 'کس سے',
    eng: 'From what',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: orange,
    n: '4',
    name: 'فِیْمَ',
    urdu: 'کس میں',
    eng: 'In what',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: darkGreen,
    n: '5',
    name: 'لِمَنْ',
    urdu: 'کس لے لیے',
    eng: 'For who',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: red,
    n: '6',
    name: 'مِمَّنْ',
    urdu: 'کس شخص سے',
    eng: 'From which person',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: yellow,
    n: '2',
    name: 'اِلٰی متیٰ',
    urdu: 'کب تک',
    eng: 'How long',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: torquise,
    n: '3',
    name: 'بِکَمْ',
    urdu: 'کتنے میں',
    eng: 'In how much',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: orange,
    n: '4',
    name: 'مِنْ اَیْنَ',
    urdu: 'کہاں تک',
    eng: 'From where',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: darkGreen,
    n: '5',
    name: 'اِلٰی اَیْنَ',
    urdu: 'کہاں تک',
    eng: 'How far',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: 'Interogative Nouns with prepositions',
    subheading: 'حروف جارہ کے ساتھ',
    color: red,
    n: '6',
    name: 'لِمَاذَا',
    urdu: 'کیوں',
    eng: 'Why',
    g: ' ',
  ),
];
