import '../constants.dart';
import '../data.dart';
import 'words_data.dart';

List<WordsData> internoun = [
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'مَا',
    urdu: 'کیا',
    eng: 'What',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'مَنْ',
    urdu: 'کون',
    eng: 'Who',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'کَیْفَ',
    urdu: 'کیسا',
    eng: 'How',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَیْنَ',
    urdu: 'کہاں',
    eng: 'Where',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'مَتیٰ',
    urdu: 'کب',
    eng: 'When',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَیَّانَ',
    urdu: 'کب',
    eng: 'When',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَنّٰی',
    urdu: 'کہاں سے',
    eng: 'Where from',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَیُّ',
    urdu: 'کونسا',
    eng: 'Which',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'کَمْ',
    urdu: 'کتنا',
    eng: 'How many',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'لِمَاذَا',
    urdu: 'کیوں',
    eng: 'Why',
    g: ' ',
  ),
  WordsData(
    urduheading: 'اسماء استفہام',
    engheading: quranTopics[10].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'لَوْلَا',
    urdu: 'کیوں نہیں',
    eng: 'Why not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف استفہام',
    engheading: 'Interogative Words',
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اَ',
    urdu: 'کیا',
    eng: 'What',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف استفہام',
    engheading: 'Interogative Words',
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'ھَلْ',
    urdu: 'کیا',
    eng: 'What',
    g: ' ',
  ),
];
