import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> makan = [
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'فَوقَ',
    urdu: 'اوپر',
    eng: 'On top',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'تَحْتَ',
    urdu: 'نیچے',
    eng: 'Under',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَمَامَ',
    urdu: 'آگے/ سامنے',
    eng: 'In Front',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'خَلَفَ',
    urdu: 'پیچھے',
    eng: 'Behind',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'وَرَآءَ',
    urdu: 'پیچھے/ سوا',
    eng: 'Behind/ except',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'یَمِیْنَ',
    urdu: 'دائیں',
    eng: 'Right side',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'شِمَالَ',
    urdu: 'بائیں',
    eng: 'Left side',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بَیْنَ',
    urdu: 'درمیان',
    eng: 'Between',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'وَسَطَ',
    urdu: 'درمیان',
    eng: 'Between',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'بَیْنَ اَیْدِی',
    urdu: 'سامنے',
    eng: 'In front',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'حَوْلَ',
    urdu: 'اطراف',
    eng: 'Around',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'حَیْثُ',
    urdu: 'جس جگہ',
    eng: 'The Place where',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'مَعَ',
    urdu: 'ساتھ',
    eng: 'with',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'عِنْدَ',
    urdu: 'پاس/ کی طرف سے',
    eng: ' by/ at',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'ھُنَا',
    urdu: 'یہاں',
    eng: 'here',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'ھُنَاکَ',
    urdu: 'وہاں',
    eng: 'there',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'بَعِیْدٌ',
    urdu: 'دور',
    eng: 'far',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'قَرِیْبٌ',
    urdu: 'نزدیک',
    eng: 'near',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'أسْفَلَ',
    urdu: 'نیچے',
    eng: 'Beneath',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف المکان',
    engheading: quranTopics[7].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'أَعْلٰی',
    urdu: 'اوپر',
    eng: 'Above',
    g: ' ',
  )
];
