import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> izafi = [
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'نِعْمَةُ اللّٰہِ',
    urdu: 'اللّٰہ کی نعمت',
    eng: 'A blessing of Allah',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'رَبُّ الْعَالَمِیْنَ',
    urdu: 'تمام جہانوں کا رب',
    eng: 'The Lord of the universe',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'قَلُوْبُ الْمُؤْمِنِیْنَ',
    urdu: 'مؤمنوں کے دل',
    eng: 'The hearts of believers',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَصْحٰبُ الْجَنَّةِ',
    urdu: 'جنت والے',
    eng: 'Paradise people',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'نَصْرُ اللّٰہِ',
    urdu: 'اللّٰہ کی مدد',
    eng: "The help of Allah",
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '14',
    name: 'قَوْمُ لُوْطٍ',
    urdu: 'لوط کی قوم',
    eng: 'The people of Loot',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'عَالِمُ الْغَیْبِ',
    urdu: 'غیب کا جاننے والا',
    eng: 'The Knower of the unseen',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'رَسُوْلُ اللّٰہِ',
    urdu: 'اللّٰہ کا رسول',
    eng: 'The messenger of Allah',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'مُقِیْمَ الصَّلٰوةِ',
    urdu: 'نماز کا قائم کرنے والا',
    eng: "Establisher of the prayer",
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اضافی',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'عَبْدُ اللّٰہِ',
    urdu: 'اللّٰہ کا بندہ',
    eng: 'The slave of Allah',
    g: ' ',
  )
];

List<WordsData> ishari = [
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'ھٰذَا الْبَلَدِ الْأمِیْنِ',
    urdu: 'یہ امن والا شہر ',
    eng: 'This secure city',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'ھٰذَانِ خَصْمٰنِ',
    urdu: 'یہ دو فریق',
    eng: 'These two opponents',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'ھٰؤُلٓاءِ لَضَآلُّوْنَ',
    urdu: 'یہ لوگ یقیناً گمراہ ہیں',
    eng: 'These surely have gone astray',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'ھٰذِہِ الْحَیَاةُ الدُّنْیَا',
    urdu: 'یہ دنیاوی زندگی',
    eng: 'This life of the world',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'ذٰلِکَ الْکِتَابُ',
    urdu: '(یہ) وہ کتاب',
    eng: 'That book',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'ذَانِکَ بُرْھٰنَانِ',
    urdu: '(وہ) یہ دونوں نشانیاں',
    eng: 'These twi evidences',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اُولٓئِکَ الَّذِیْنَ',
    urdu: 'وہی لوگ ہیں جنہوں نے',
    eng: 'Those the ones who',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب اشاری',
    engheading: quranTopics[15].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'تِلْکَ الْجَنَّةِ',
    urdu: 'وہ جنت',
    eng: 'That paradise',
    g: ' ',
  )
];

List<WordsData> jarri = [
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'بِسْمِ اللّٰہِ',
    urdu: 'اللّٰہ کے نام کے ساتھ ',
    eng: 'In the name of Allah',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'لِلّٰہِ',
    urdu: 'اللّٰہ کے لیے',
    eng: 'To Allah',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'وَالْقَلَمِ',
    urdu: 'قلم کی قسم',
    eng: 'By the pen',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'کَالْمُجْرِمِیْنَ',
    urdu: 'گناہگاروں کی طرح',
    eng: 'Like the criminals',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'فِیْ سَبِیْلِ اللّٰہِ',
    urdu: 'اللّٰہ کے راستے میں ',
    eng: 'In the way of Allah',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'مِنْ عِنْدِ اللّٰہِ',
    urdu: 'اللّٰہ کے پاس سے',
    eng: 'From Allah',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'إِلَی الْاَرْضِ',
    urdu: 'زمین کی طرف',
    eng: 'Towards the earth',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'عَلٰی قُلُوْبِھِمْ',
    urdu: 'انکے دلوں پر',
    eng: 'On their hearts',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'حَتّٰی حِیْن',
    urdu: 'ایک وقت تک',
    eng: 'Until a time',
    g: ' ',
  ),
  WordsData(
    urduheading: quranTopics[16].topic,
    engheading: quranTopics[16].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'لِلْمُتَّقِیْنَ',
    urdu: 'پرہیزگاروں کے لیے',
    eng: 'For the righteous',
    g: ' ',
  ),
];

List<WordsData> tausefi = [
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اٰیٰتٌ بَیِّنٰتٌ',
    urdu: 'کھلی نشانیاں',
    eng: 'Clear signs',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اَلصِّرَاطُ الْمُسْتَقِیْمُ',
    urdu: 'سیدھا راستہ',
    eng: 'The straight path',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'عَرْشٌ عَظِیْمٌ',
    urdu: 'بہت بڑا عرش',
    eng: 'Great throne',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'شَیْئٌ عَجِیْبٌ',
    urdu: 'عجیب چیز',
    eng: 'An amazing thing',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'عَذَابًا عَلِیْمًا',
    urdu: 'دردناک عذاب',
    eng: 'Painful punishment',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اَلْقُرَآنِ الْحَکِیْمِ',
    urdu: 'حکمت والا قرآن',
    eng: 'The wise Quran',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'بَقَرَةٌ صَفْرَآءُ',
    urdu: 'زرد گائے',
    eng: 'A Yellow Cow',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'عَمَلٌ صَالِحٌ',
    urdu: 'نیک کام',
    eng: 'A righteous deed',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'عَدُوٌّ مُبِیْنٌ',
    urdu: 'کھلا دشمن',
    eng: 'A clear enemy',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مرکب توصیفی',
    engheading: quranTopics[17].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اَیَّامٌ مَّعْدُوْدَةٌ',
    urdu: 'چند دن',
    eng: 'A few days',
    g: ' ',
  ),
];
