import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> negative = [
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'مَا',
    urdu: 'نہیں (ماضی)',
    eng: 'Did not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'لَا',
    urdu: 'نہیں (مضارع)',
    eng: 'Do not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'لَمْ',
    urdu: 'نہیں',
    eng: 'Have not/ Did not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'لَمَّا',
    urdu: 'ابھی تک نہیں',
    eng: 'Still not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'لَنْ',
    urdu: 'ہر گز نہیں',
    eng: 'Will not/ Not at all',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'کَلَّا',
    urdu: 'ہر گز نہیں',
    eng: 'No',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'فَلَا',
    urdu: 'پس نہیں/ خبردار',
    eng: 'so do not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'لَیْسَ',
    urdu: 'نہیں ہو گا/ ہے',
    eng: 'is/ will not',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف نفی',
    engheading: quranTopics[9].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'فَلَوْلَا',
    urdu: 'پھر اگر نہ ہوتا',
    eng: 'so if not',
    g: ' ',
  ),
];
