import 'words_data.dart';

import '../constants.dart';

List<WordsData> prepMaa = [
  WordsData(
    urduheading: 'حروف جارہ + مَا',
    engheading: 'Preposition + Maa',
    subheading: ' ',
    color: red,
    n: '1',
    name: 'بِمَا',
    urdu: 'کے ساتھ جو',
    eng: 'With who',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + مَا',
    engheading: 'Preposition + Maa',
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'عَمَّا',
    urdu: 'کے بارے میں جو',
    eng: 'In regards to',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + مَا',
    engheading: 'Preposition + Maa',
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'فِیْمَا',
    urdu: 'اس میں جو',
    eng: 'In that',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + مَا',
    engheading: 'Preposition + Maa',
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'کَمَا',
    urdu: 'جیسا کہ',
    eng: 'Like',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + مَا',
    engheading: 'Preposition + Maa',
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'لِمَا',
    urdu: 'اس لئے جو',
    eng: "That's why",
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + مَا',
    engheading: 'Preposition + Maa',
    subheading: ' ',
    color: red,
    n: '6',
    name: 'لَمَّا',
    urdu: 'جب بھی',
    eng: 'Whenever',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + مَا',
    engheading: 'Preposition + Maa',
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'مِمَّا',
    urdu: 'اس میں سے جو',
    eng: 'Of which that',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'اَمَّا',
    urdu: 'جس نے/ جو',
    eng: 'Who',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'فَبِمَا',
    urdu: 'پس بوجہ اس کے جو',
    eng: "so that's why",
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَنَّمَا',
    urdu: 'بے شک جو',
    eng: 'Indeed',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اِنَّمَا',
    urdu: 'بے شک/ صرف جو',
    eng: 'Only that',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'کَأَنَّمَا',
    urdu: ' گویا کہ جو',
    eng: 'As if',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'کُلَّمَا',
    urdu: 'جب بھی',
    eng: 'Whenever',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'فَلَمَّا',
    urdu: 'پس جب',
    eng: 'So when',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اَیْنَمَا',
    urdu: 'کہیں بھی',
    eng: 'Whenever',
    g: ' ',
  ),
  WordsData(
    urduheading: 'مَا_',
    engheading: '_Maa',
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مَھْمَا',
    urdu: ' کیسا ہی',
    eng: 'Whatever',
    g: ' ',
  )
];
