import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> prep = [
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'بِ',
    urdu: 'کے ساتھ',
    eng: 'With',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'تَ ',
    urdu: 'حرف قسم',
    eng: 'Promise by',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'وَ',
    urdu: 'حرف قسم',
    eng: 'Promise by',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'كَ',
    urdu: 'کی طرح',
    eng: 'Like',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'فِىْ',
    urdu: 'میں',
    eng: 'In',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مِنْ',
    urdu: 'سے',
    eng: 'From',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'عَنْ',
    urdu: 'سے',
    eng: 'About',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'إِلٰی',
    urdu: 'کی طرف',
    eng: 'To',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'عَلٰى',
    urdu: 'پر',
    eng: 'On',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'حَتّٰى',
    urdu: 'تک',
    eng: 'Till',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مِنْ',
    urdu: 'سے',
    eng: 'From',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'لِ',
    urdu: 'کے لیے',
    eng: 'For',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'مُذْ',
    urdu: 'سے',
    eng: 'For',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'مُنْذُ',
    urdu: 'سے',
    eng: 'For',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'خَلَا',
    urdu: 'سوائے',
    eng: 'Except',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'حَاشَا',
    urdu: 'سوائے',
    eng: 'Except',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'عَدَا',
    urdu: 'سوائے',
    eng: 'Except',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ',
    engheading: quranTopics[3].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'رُبَّ',
    urdu: 'چند',
    eng: 'Some',
    g: ' ',
  ),
];
