import 'words_data.dart';

import '../constants.dart';

List<WordsData> pronoun = [
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: red,
    n: '1',
    name: 'ھُوَ',
    urdu: 'وہ (مذکر)',
    eng: 'He',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: yellow,
    n: '2',
    name: 'ھُمَا',
    urdu: 'وہ دو (مذکر و مؤنث)',
    eng: 'They two',
    g: '(M+F)',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: torquise,
    n: '3',
    name: 'ھُمْ',
    urdu: 'وہ سب (مزکر)',
    eng: 'They all',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: orange,
    n: '4',
    name: 'ھِیَ',
    urdu: 'وہ (مؤنث)',
    eng: 'She',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: darkGreen,
    n: '5',
    name: 'ھُنَّ',
    urdu: 'وہ سب مؤنث',
    eng: 'They all',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: red,
    n: '6',
    name: 'اَنْتَ',
    urdu: 'تم (ایک مذکر)',
    eng: 'You',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: yellow,
    n: '7',
    name: 'اَنْتُمَا',
    urdu: ' تم دو (مذکر و مؤنث)',
    eng: 'Both of you',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: torquise,
    n: '8',
    name: 'اَنْتُمْ',
    urdu: 'تم سب (مذکر)',
    eng: 'All of you',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: orange,
    n: '9',
    name: 'اَنْتِ',
    urdu: 'تم ایک (مؤنث)',
    eng: 'You',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: darkGreen,
    n: '10',
    name: 'اَنْتُنَّ',
    urdu: 'تم سب (مؤنث)',
    eng: 'All of you',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: red,
    n: '11',
    name: 'اَنَا',
    urdu: 'میں',
    eng: 'I',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر منفصل',
    engheading: ' ',
    subheading: 'Independent Pronouns - رفع',
    color: yellow,
    n: '12',
    name: 'نَحْنُ',
    urdu: 'ہم',
    eng: 'We',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: torquise,
    n: '13',
    name: 'ہُ-',
    urdu: 'اس کا (ایک مذکر)',
    eng: 'His',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: orange,
    n: '14',
    name: 'ھُمَا-',
    urdu: 'ان دو کا (مذکر و مؤنث)',
    eng: 'Their (two)',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: red,
    n: '15',
    name: 'ھُمْ-',
    urdu: 'ان سب کا (مذکر)',
    eng: 'All of them',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: darkGreen,
    n: '16',
    name: 'ھَا-',
    urdu: 'اس کا (ایک مؤنث)',
    eng: 'Her',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: red,
    n: '17',
    name: 'ھُنَّ-',
    urdu: 'ان سب کا (مؤنث)',
    eng: 'All of them',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: yellow,
    n: '18',
    name: 'كَ-',
    urdu: 'تمہارا (مذکر)',
    eng: 'Your',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: torquise,
    n: '19',
    name: 'کُمَا-',
    urdu: ' تم دو کا (مذکر مؤنث)',
    eng: 'Your (two)',
    g: '(M + F)',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: orange,
    n: '20',
    name: 'کُمْ-',
    urdu: 'تم سب کا (مذکر)',
    eng: 'Your (all)',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: darkGreen,
    n: '21',
    name: 'كِ-',
    urdu: 'تمہارا (مؤنث)',
    eng: 'Your',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: red,
    n: '22',
    name: 'کُنَّ-',
    urdu: 'تم سب کا (مؤنث)',
    eng: 'Your (all)',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: yellow,
    n: '23',
    name: 'یَ',
    urdu: 'میرا',
    eng: 'Mine',
    g: '',
  ),
  WordsData(
    urduheading: 'ضمائر متصل',
    engheading: ' ',
    subheading: 'Attached Pronouns - نصب و جر',
    color: torquise,
    n: '24',
    name: 'نَا-',
    urdu: 'ہمارا',
    eng: 'Our',
    g: '',
  ),
];
