import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> rp = [
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'رفع',
    color: red,
    n: '1',
    name: 'اَلَّذِی',
    urdu: 'جو (مفرد مذکر)',
    eng: 'Who',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'رفع',
    color: yellow,
    n: '2',
    name: 'اَللَّذَانِ',
    urdu: '(تثنیہ مذکر)',
    eng: 'Who Two',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'رفع',
    color: torquise,
    n: '3',
    name: 'الَّذِیْنَ',
    urdu: '(جمع مذکر)',
    eng: 'Who All',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'رفع',
    color: orange,
    n: '4',
    name: 'الَّتِی',
    urdu: '(مفرد مؤنث)',
    eng: 'Who',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'رفع',
    color: darkGreen,
    n: '5',
    name: 'اللَّتَانِ',
    urdu: '(تثنیہ مؤنث)',
    eng: 'Who Two',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'رفع',
    color: red,
    n: '6',
    name: 'اللَّاتِی',
    urdu: '(جمع مؤنث)',
    eng: 'Who All',
    g: '(F)',
  ),
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'نصب و جر',
    color: yellow,
    n: '13',
    name: 'اَللَّذَیْنِ',
    urdu: ' جو دو (تثنیہ مذکر)',
    eng: 'Who two',
    g: '(M)',
  ),
  WordsData(
    urduheading: 'اسماء موصولہ',
    engheading: quranTopics[2].eng.capitalize(),
    subheading: 'نصب و جر',
    color: torquise,
    n: '14',
    name: 'اَللَّتَیْنِ',
    urdu: 'جو دو (تثنیہ مؤنث)',
    eng: 'Who Two',
    g: '(F)',
  ),
];
