import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> sentences = [
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'اِنَّ اللّٰہَ عَلَی کُلِّ شَئٍ قَدِیْرٌ',
    urdu: 'بے شک اللہ تعالیٰ ہر چیز پر قادر ہے۔',
    eng: 'Verily, Allah is able to do all things.',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'وَاللّٰہُ خَبِیْرٌۢ بِمَا تَعْمَلُوْنَ',
    urdu: 'اور اللّٰہ تمہارے اعمال سے خبردار ہے۔',
    eng: 'And Allah is aware of your actions.',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'وَلَذِکْرُ اللّٰہِ أَکْبَرْ ',
    urdu: 'اور اللّٰہ کا ذکر بڑا ہے۔',
    eng: 'And the mention of Allah is great.',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اِنَّ اللّٰہ ھُوَ الغَفُوْرُ الرَّحِیْمُ',
    urdu: 'بےشک اللّٰہ بخشنے والا رحم کرنے والا ہے۔',
    eng: "Indeed, Allah is oft-forgiving, Most Merciful.",
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '18',
    name: 'إِنَّکَ أَنْتَ التَّوَّابُ الرَّحِیْمُ',
    urdu: 'بےشک تو رحم کرنے والا توبہ قبول کرنے والا ہے۔',
    eng: 'Indeed, You are the Accepting of repentance, the Merciful',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'اِنَّہٗ ھُوَ السَّمِیْعُ العَلِیْمُ',
    urdu: 'بےشک وہ سننے والا جاننے والا ہے۔',
    eng: 'Verily, He is the Hearer the Knower.',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اِنَّھُمْ ھُمُ السُّفَھَاءُ',
    urdu: 'بے شک وہ بےوقوف ہیں۔',
    eng: "Indeed, they are fouls.",
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'وَاِلٰھُکُمْ إِلٰہٌ وَّاحِدٌ',
    urdu: 'اور تمہارا معبود ایک ہی معبود ہے۔',
    eng: 'And your God is one God.',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '13',
    name: 'وَاِنِّیْ عَبْدُ اللّٰہِ',
    urdu: 'اور بےشک میں اللّٰہ کا بندہ ہوں۔',
    eng: 'Indeed, I am a servant of Allah.',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '14',
    name: 'إِنَّنِیْ أَنَا اللّٰہُ',
    urdu: 'بےشک میں ہی اللّٰہ ہوں۔',
    eng: 'Indeed, I am Allah.',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اُولٰٓئِکَ ھُمُ الْمُفْلِحُوْنَ',
    urdu: 'وہی لوگ فلاح پانے والے ہیں۔',
    eng: "Those are the people who will benefit.",
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق جملے',
    engheading: quranTopics[18].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اِنَّ بَطْشَ رَبِّکَ لَشَدِیْدٌ',
    urdu: 'بےشک تمہارے رب کی پکڑ سخت ہے۔',
    eng: 'Verily, the grip of your Lord is severe.',
    g: ' ',
  ),
];
