import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> signs = [
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'آیةٌ',
    urdu: 'آیت',
    eng: 'Verses',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'جَبَلٌ',
    urdu: 'پہاڑ',
    eng: 'Mountain',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بَحْرٌ',
    urdu: 'سمندر',
    eng: 'Sea',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'شَمْسٌ',
    urdu: 'سورج',
    eng: 'Sun',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'قَمَرٌ',
    urdu: 'چاند',
    eng: 'Moon',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'لَیْلٌ',
    urdu: 'رات',
    eng: 'Night',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'نَہَارٌ',
    urdu: 'دن',
    eng: 'Day',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَرْضٌ',
    urdu: 'زمین',
    eng: 'Earth',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'صُبْحٌ',
    urdu: 'صبح',
    eng: 'Morning',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'مَسَاءٌ',
    urdu: 'شام',
    eng: 'Evening',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'رِیْحٌ',
    urdu: 'ہوا',
    eng: 'Wind',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'صَرْصَرٌ',
    urdu: 'ہوا',
    eng: 'Wind',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بَادٍ',
    urdu: 'ہوا',
    eng: 'Wind',
    g: ' ',
  ),
  WordsData(
    urduheading: 'نشانیاں',
    engheading: twoTopics[12].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'سَمُوْمٌ',
    urdu: 'ہوا',
    eng: 'Wind',
    g: ' ',
  ),
];
