import 'package:quranic_words/Models/words_data.dart';

import '../constants.dart';
import '../data.dart';

List<WordsData> seprated = [
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'عسٰی',
    urdu: 'امید ہے',
    eng: 'expected/ Perhaps',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'لَوْ',
    urdu: 'اگر',
    eng: 'if',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اِیَّا',
    urdu: 'ہی',
    eng: 'just',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اِلَّا',
    urdu: 'مگر/ سوائے',
    eng: 'except',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'یَا',
    urdu: 'اے',
    eng: 'calling word',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اِذَا',
    urdu: 'جب',
    eng: 'if/ when',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اِذْ',
    urdu: 'جب سے/ جبکہ',
    eng: 'since/ when',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اِذًا',
    urdu: 'لہذا/ اس لئے',
    eng: 'hence, Therefore',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'کَذَالِکَ',
    urdu: 'اسی طرح',
    eng: 'thus',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'قَدْ',
    urdu: 'تاکید کے لئے',
    eng: 'for emphasis',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'لَقَدْ',
    urdu: 'البتّہ/ تحقیق',
    eng: 'for emphasis',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'سَوْفَ/ سَ',
    urdu: 'عنقریب',
    eng: 'soon',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'مِثْلَ',
    urdu: 'مثال',
    eng: 'example',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'أَھْلَ',
    urdu: 'والا/ گھروالے',
    eng: 'people/ family',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'اُولُو',
    urdu: 'لوگ/ والے',
    eng: 'people',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'ذُو-ذِی-ذَا',
    urdu: 'والے',
    eng: 'the owner',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'اٰلَ',
    urdu: ' گھروالے/ قوم',
    eng: 'nation/ family',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بَلٰی',
    urdu: 'کیوں نہیں',
    eng: 'why not/ yes',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَلَا',
    urdu: 'خبردار/ سن رکھو',
    eng: 'unquestionably',
    g: ' ',
  ),
  WordsData(
    urduheading: 'متفرق حروف',
    engheading: quranTopics[14].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '4',
    name: 'بَلْ',
    urdu: 'بلکہ',
    eng: 'but/ infact',
    g: ' ',
  ),
];
