import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> withprep = [
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'بِهٖ',
    urdu: 'اس (مذکر) کے ساتھ',
    eng: 'With his',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '1',
    name: 'بِھَا',
    urdu: 'اس (موٴنث) کے ساتھ',
    eng: 'With her',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '5',
    name: 'فِيْهِ',
    urdu: 'اس (مذکر) میں',
    eng: 'In the',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '5',
    name: 'فِيْھِمَا',
    urdu: 'ان دونوں (مذکر و موٴنث) میں',
    eng: 'In the',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '6',
    name: 'مِنْهُ',
    urdu: 'اس (مذکر) سے',
    eng: 'From him',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '6',
    name: 'مِنْھُمْ',
    urdu: 'ان سب (مذکر) سے',
    eng: 'From them',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '13',
    name: 'عَنْہُ',
    urdu: 'اس (مذکر) سے',
    eng: 'With him',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '13',
    name: 'عَنْھُنَّ',
    urdu: 'ان سب (موٴنث) سے',
    eng: 'With them',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '14',
    name: 'اِلَیهٖ',
    urdu: 'اس کی طرف',
    eng: 'To',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '4',
    name: 'عَلَیْھِمْ',
    urdu: 'اُن (مذکر) پر',
    eng: 'On them',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'عَلیَّ',
    urdu: 'مجھ پر',
    eng: 'On me',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'حَتّٰى',
    urdu: 'یہان تک کہ',
    eng: 'Till',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'لَهٗ',
    urdu: 'اس (مذکر) کے لیے',
    eng: 'For him',
    g: ' ',
  ),
  WordsData(
    urduheading: 'حروف جارہ + ضمائر',
    engheading: quranTopics[4].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '6',
    name: 'لَھُمْ',
    urdu: 'اُن (مذکر) کے لیے',
    eng: 'For them',
    g: ' ',
  )
];
