import '../data.dart';
import 'words_data.dart';

import '../constants.dart';

List<WordsData> zaman = [
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '1',
    name: 'سَاعَةٌ',
    urdu: 'گھڑی',
    eng: 'hour',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'یَوْمٌ',
    urdu: 'دن',
    eng: 'day',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اُسْبُوْعٌ',
    urdu: 'ہفتہ',
    eng: 'week',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'شَہْرٌ',
    urdu: 'مہینہ',
    eng: 'month',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'سَنَةٌ/ عَامٌ',
    urdu: 'سال',
    eng: 'year',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'قَرْنٍ',
    urdu: 'صدی',
    eng: 'century',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'قَبْلَ',
    urdu: 'پہلے',
    eng: 'Before',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'بَعْدَ',
    urdu: 'بعد میں',
    eng: 'After',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَثْنَآءَ',
    urdu: 'دوران',
    eng: 'During',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'صَبَاحٌ',
    urdu: 'صبح',
    eng: 'Morning',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'مَسَآءٌ/ اَصِیْلًا',
    urdu: 'شام',
    eng: 'Evening',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'فَتْرَةٌ/ مُدَّةٌ',
    urdu: 'مدت',
    eng: 'Duration',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'غَداً',
    urdu: 'آنے والا کل',
    eng: 'Tomorrow',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'بُکْرَةً',
    urdu: 'صبح سویرے',
    eng: 'Early Morning',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'حِیْنَ',
    urdu: 'وقت',
    eng: 'Period',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: red,
    n: '6',
    name: 'اَلْآَنَ',
    urdu: 'ابھی',
    eng: 'Now',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: yellow,
    n: '2',
    name: 'دَائِمًا',
    urdu: 'ہمیشہ',
    eng: 'Always',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: torquise,
    n: '3',
    name: 'اَحْیَانًا',
    urdu: 'کبھی کبھار',
    eng: 'Sometimes',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: orange,
    n: '4',
    name: 'اَبَدًا',
    urdu: 'ہمیشہ',
    eng: 'Forever',
    g: ' ',
  ),
  WordsData(
    urduheading: 'ظروف الزَّمَان',
    engheading: quranTopics[8].eng.capitalize(),
    subheading: ' ',
    color: darkGreen,
    n: '5',
    name: 'دَھْرِ',
    urdu: 'زمانہ',
    eng: 'The time',
    g: ' ',
  )
];
